import DOMPurify from 'dompurify'
import { AlertCircle, Code, Eye, Loader2, Save } from 'lucide-react'
import { useState } from 'react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'

interface CustomHTMLPreviewProps {
  className?: string
}

export function CustomHTMLPreview({ className }: CustomHTMLPreviewProps) {
  const [htmlContent, setHtmlContent] = useState(getDefaultHTML())
  const [previewMode, setPreviewMode] = useState<'edit' | 'preview'>('edit')
  const [validationError, setValidationError] = useState<string | null>(null)
  const [sanitizedHTML, setSanitizedHTML] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)

  function getDefaultHTML(): string {
    return `<!-- Add your custom HTML here -->
<div class="p-8 space-y-6">
  <h1 class="text-4xl font-bold text-foreground">Custom HTML Preview</h1>
  
  <p class="text-lg text-muted-foreground">
    This component uses your design system tokens automatically.
    Try adding buttons, cards, forms, and more!
  </p>

  <div class="flex gap-4">
    <button class="btn btn-primary">
      Primary Button
    </button>
    <button class="btn btn-secondary">
      Secondary Button
    </button>
    <button class="btn btn-outline">
      Outline Button
    </button>
  </div>

  <div class="card p-6">
    <h2 class="text-2xl font-semibold mb-2">Card Component</h2>
    <p class="text-muted-foreground">
      This card uses the design system's card styles.
    </p>
  </div>

  <div class="alert alert-info">
    <strong>Info:</strong> You can use all the utility classes generated by your design system.
  </div>
</div>`
  }

  function validateAndSanitizeHTML(html: string): void {
    setValidationError(null)

    try {
      // Basic validation - check for balanced tags
      const parser = new DOMParser()
      const doc = parser.parseFromString(html, 'text/html')
      const parserError = doc.querySelector('parsererror')

      if (parserError) {
        setValidationError(`Invalid HTML: ${parserError.textContent}`)
        return
      }

      // Sanitize HTML to prevent XSS
      const clean = DOMPurify.sanitize(html, {
        ALLOWED_TAGS: [
          'div',
          'span',
          'p',
          'h1',
          'h2',
          'h3',
          'h4',
          'h5',
          'h6',
          'button',
          'a',
          'ul',
          'ol',
          'li',
          'strong',
          'em',
          'code',
          'pre',
          'blockquote',
          'img',
          'section',
          'article',
          'header',
          'footer',
          'nav',
          'aside',
          'main',
          'table',
          'thead',
          'tbody',
          'tr',
          'th',
          'td',
          'form',
          'input',
          'textarea',
          'label',
          'select',
          'option',
          'svg',
          'path',
          'circle',
          'rect',
          'line',
          'polyline',
          'polygon',
        ],
        ALLOWED_ATTR: [
          'class',
          'id',
          'href',
          'src',
          'alt',
          'title',
          'type',
          'placeholder',
          'value',
          'name',
          'for',
          'viewBox',
          'd',
          'fill',
          'stroke',
          'stroke-width',
          'width',
          'height',
          'x',
          'y',
          'cx',
          'cy',
          'r',
          'points',
        ],
        FORBID_TAGS: ['script', 'style', 'iframe', 'object', 'embed'],
        FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover'],
      })

      setSanitizedHTML(clean)

      // Save to localStorage
      try {
        localStorage.setItem('custom-html-preview', html)
      } catch (e) {
        console.warn('Failed to save custom HTML to localStorage:', e)
      }
    } catch (error) {
      setValidationError(
        `Failed to validate HTML: ${error instanceof Error ? error.message : 'Unknown error'}`,
      )
    }
  }

  function handlePreview() {
    setIsProcessing(true)
    // Simulate processing time for validation
    setTimeout(() => {
      validateAndSanitizeHTML(htmlContent)
      if (!validationError) {
        setPreviewMode('preview')
      }
      setIsProcessing(false)
    }, 300)
  }

  function handleReset() {
    const defaultHTML = getDefaultHTML()
    setHtmlContent(defaultHTML)
    validateAndSanitizeHTML(defaultHTML)
    setPreviewMode('edit')
  }

  function handleSave() {
    validateAndSanitizeHTML(htmlContent)
    if (!validationError) {
      alert('HTML saved to browser storage!')
    }
  }

  // Load saved HTML on mount
  useState(() => {
    try {
      const saved = localStorage.getItem('custom-html-preview')
      if (saved) {
        setHtmlContent(saved)
        validateAndSanitizeHTML(saved)
      }
    } catch (e) {
      console.warn('Failed to load saved HTML:', e)
    }
  })

  return (
    <div className={className}>
      <div className="flex items-center justify-between border-b border-border bg-card px-4 py-3">
        <div className="flex items-center gap-2">
          <Code className="h-5 w-5 text-muted-foreground" />
          <h2 className="text-lg font-semibold text-foreground">
            Custom HTML Preview
          </h2>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant={previewMode === 'edit' ? 'default' : 'outline'}
            size="sm"
            onClick={() => setPreviewMode('edit')}
          >
            <Code className="mr-2 h-4 w-4" />
            Edit
          </Button>
          <Button
            variant={previewMode === 'preview' ? 'default' : 'outline'}
            size="sm"
            onClick={handlePreview}
            disabled={isProcessing}
          >
            {isProcessing ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <Eye className="mr-2 h-4 w-4" />
                Preview
              </>
            )}
          </Button>
          <Button variant="outline" size="sm" onClick={handleSave}>
            <Save className="mr-2 h-4 w-4" />
            Save
          </Button>
          <Button variant="ghost" size="sm" onClick={handleReset}>
            Reset
          </Button>
        </div>
      </div>

      {validationError && (
        <Alert variant="destructive" className="m-4">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{validationError}</AlertDescription>
        </Alert>
      )}

      {previewMode === 'edit' ? (
        <div className="p-4">
          <Label
            htmlFor="html-editor"
            className="text-sm font-medium text-foreground"
          >
            HTML Content
          </Label>
          <textarea
            id="html-editor"
            value={htmlContent}
            onChange={(e) => setHtmlContent(e.target.value)}
            className="mt-2 h-[600px] w-full rounded-md border border-input bg-background px-3 py-2 font-mono text-sm text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
            placeholder="Enter your HTML here..."
            spellCheck={false}
          />

          <div className="mt-4 rounded-md bg-muted p-4">
            <h3 className="mb-2 text-sm font-semibold text-foreground">
              Available CSS Classes:
            </h3>
            <div className="grid grid-cols-2 gap-2 text-sm text-muted-foreground md:grid-cols-3">
              <div>
                <strong className="text-foreground">Buttons:</strong> btn,
                btn-primary, btn-secondary, btn-outline, btn-ghost
              </div>
              <div>
                <strong className="text-foreground">Cards:</strong> card,
                card-hover
              </div>
              <div>
                <strong className="text-foreground">Alerts:</strong> alert,
                alert-info, alert-success, alert-warning, alert-error
              </div>
              <div>
                <strong className="text-foreground">Badges:</strong> badge,
                badge-primary, badge-success, badge-warning, badge-error
              </div>
              <div>
                <strong className="text-foreground">Text:</strong>{' '}
                text-foreground, text-muted-foreground
              </div>
              <div>
                <strong className="text-foreground">Spacing:</strong> p-*, m-*,
                gap-*, space-*
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-4">
          <div
            className="rounded-md border border-border bg-background"
            // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is sanitized with DOMPurify
            dangerouslySetInnerHTML={{ __html: sanitizedHTML }}
          />
        </div>
      )}
    </div>
  )
}
